geo_acc:  GSE76091
pmid:     XXX
descrip:  Diverse fates of uracilated HIV DNA during infection of myeloid lineage cells

samples:
    - SRR3026044
    - SRR1158613

descriptions: 
    - "MDM Day 7 -UDG"
    - "MDM Day 7 +UDG"

short_descrip:
    - "MDM Day 7 -UDG"
    - "MDM Day 7 +UDG"

urls:
     - ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByExp/sra/SRX%2FSRX148%2FSRX1488160/SRR3026044/SRR3026044.sra
     - ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByExp/sra/SRX%2FSRX462%2FSRX462597/SRR1158613/SRR1158613.sra

FASTA: 'data/HIV.fa.gz'
BWAIDX: 'data/HIV'
CHROMSIZE: 'data/HIV.chrom.sizes'

# vim tw=150
