#! /usr/bin/env bash

#BSUB -J dup[1-14]
#BSUB -o log/%J.%I.out
#BSUB -e log/%J.%I.err
#BSUB -R "select[mem>10] rusage[mem=10]"

set -o nounset -o pipefail -o errexit -x

source config.sh
SAMPLE=${SAMPLES[$(($LSB_JOBINDEX - 1))]}
PROJECT="/vol3/home/ransom/projects/mutation-mapping"
RESULT=$PROJECT/results/20151201
DATA=$PROJECT/results/20151116/$SAMPLE/alignment
bam="$RESULT/$SAMPLE.nodis.nochim.bam"
prefix=$SAMPLE

samtools rmdup $bam $prefix.rmdup.bam

java -jar -Xmx10g -Xms2g $HOME/software/picard-tools-1.122/MarkDuplicates.jar \
    I=$bam O=$prefix.MD.bam M=$prefix.metrics.txt REMOVE_DUPLICATES=TRUE
